# -*- coding: utf-8 -*-
"""Тестовое задание

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pS1VQdkL23kAvjYMpM4MOdZI98ZeUo6G
"""

!pip3 install app-store-scraper

!pip3 install  beautifulsoup4

import pandas as pd

!pip3 install google_play_scraper

from google_play_scraper import reviews, Sort
import requests
import bs4
from app_store_scraper import AppStore
from pprint import pprint



def get_company(app):
    r = requests.get("https://play.google.com/store/search?q=" + app + "&c=apps")
    soup = bs4.BeautifulSoup(r.text, "html.parser")
    #/html/body/div[1]/div[4]/c-wiz[3]/div/div[2]/div/c-wiz/c-wiz/c-wiz/div/div[2]/div[1]/c-wiz/div/div/div[2]/div/a
    subtitles = soup.findAll("c-wiz")[4].findAll("a")
    return (subtitles[4].get('href'))

name_g, text_g, count_star_g, source_g, date_g = [],[],[],[],[]
my_app = input()
dev_urls = get_company(my_app)
dev_urls = (dev_urls[23:])
print(dev_urls)
link = ""
while result[len(result) - 1]["reviewId"] != link:
  link = result[len(result) - 1]["reviewId"]
  _, continuation_token  = reviews(
    dev_urls,
    count= 1000)
  result, _ = reviews(
    dev_urls,
    continuation_token=continuation_token 
    )
  print(result[len(result) - 1]["reviewId"], link)
  
  for i in range(len(result)):
    name_g.append(result[i]['userName'])
    text_g.append(result[i]["content"])
    count_star_g.append(result[i]["score"])
    source_g.append("GooglePlay")
    date_g.append(result[i]["at"])
  print(len(name_g), len(text_g), len(count_star_g), len(source_g), len(date_g))
  df = pd.DataFrame({'Name user':name_g, "Review":text_g, "Count of stars":count_star_g, "Source": source_g, "Date" :date_g})

my_app_a = AppStore(country="us", app_name="viber")
my_app_a.review(how_many=1000)

z = my_app_a.reviews_count
name_a, text_a, count_star_a, source_a, date_a = [],[],[],[],[]
for i in range(z):
  name_a.append(my_app_a.reviews[i]['userName'])
  text_a.append(my_app_a.reviews[i]["review"])
  count_star_a.append(my_app_a.reviews[i]["rating"])
  source_a.append("AppStore")
  date_a.append(my_app_a.reviews[i]["date"])
df1 = pd.DataFrame({'Name user':name_a, "Review":text_a, "Count of stars":count_star_a, "Source": source_a, "Date" :date_a})

answer = pd.concat([df, df1]).sort_values(by='Date')

answer.to_csv('reviews.csv', index=True)